version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - QDRANT_URL=http://qdrant:6333
      - CLEARML_SERVER=http://clearml:8080
    depends_on:
      - mongodb
      - qdrant
      - clearml
    volumes:
      - ./app:/app  # Mount the app directory to persist changes
    command: >
      bash -c "
        pip install zenml && 
        zenml integration install docker && 
        python app.py
      "
    
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  
  clearml:
    image: allegroai/clearml:latest
    container_name: clearml
    ports:
      - "8080:8080"
    environment:
      - CLEARML_APPS=8080
    volumes:
      - clearml_data:/root/.clearml

volumes:
  mongo_data:
  qdrant_data:
  clearml_data: